### ISSUE TITLE
Infinite Loading after start logos?

### ISSUE THREAD

**Issue by gsergeantGTHB** [Joshhhuaaa/EnhancedSCDAOnline#1]
Any idea how to fix this?

**Comment by Joshhhuaaa** [comment]
SCDA Online has an issue with infinite loading screens if the game has a capped frame rate. Enhanced SCDA Online comes included to cap at 60 FPS because too high of a FPS will break the movement and camera feel in gameplay. 

As a workaround to play at 60 FPS and bypass the infinite loading screen, you have to press Ctrl+Alt+Delete when the game is loading, then press Escape to return to the game. This will force the game to load when it is unfocused. It is not ideal solution, but it's the best we have now unfortunately.

I forgot to add this to the Game Setup page and mentioned the menu failing to load. In Enhanced SCDA Online, when loading a level or returning to the lobby, the game now says press Ctrl+Alt+Delete to begin loading, so you'll know when it's time to use this workaround.

**Comment by gsergeantGTHB** [comment]
Oh so that's why, yeah you should totally make it more clear, like add it in that loading screen or something because it shows up in the other loading screens but the one at the start is probably going to turn off a lot of people because it doesn't have one, you can probably edit that video on start and add the CTRL+ALT+DEL tip there.

**Comment by Joshhhuaaa** [comment]
The "Loading..." string in the menu is not included in the localization files and was hardcoded into the executable, so I won't be able to add Ctrl+Alt+Delete as a tip there. I have updated the Game Setup section on GitHub to suggest using Ctrl+Alt+Delete if loading hangs.

Enhanced SCDA Online v2.2 will be released soon, and I've done my best to address the loading screen hang issue. Unfortunately, I wasn't able to resolve it entirely. It seems that loading screens don't work consistently even with an uncapped frame rate. In 2.2, the game will uncap FPS during loading screens and then re-cap during gameplay/menus. If you hear sounds during a loading screen, such as lobby music when starting a Versus session or ambient sounds when returning to lobby when a game finishes, you'll still need to press Ctrl+Alt+Delete to force the game to load. If no sound is present during loading, it should load normally with no action required.

I've improved it to reduce the chances of an infinite loading screen. Sometimes loading may be instant, but other times it could still hang for about 30 seconds. It's not ideal, but I couldn't find a way to completely fix it.

Using Ctrl+Alt+Delete each time is not harmful and is likely safer when connecting to other players to prevent a connection timeout. Staying on a loading screen for too long can eventually disconnect you.

Enhanced SCDA Online v2.2 will also be introducing a work in progress custom server to play online. It is not complete but the core services are working such as matchmaking, you can host/join Versus sessions, Ranked Versus sessions, and Coop Challenges. with no third party programs required to emulate a virtual LAN. There is no permanent account system in place yet, accounts are all temporary currently, so no leaderboards/squad support yet.
