### ISSUE TITLE
Ctrl+Alt+Delete on Wine

### ISSUE THREAD

**Issue by jf99** [Joshhhuaaa/EnhancedSCDAOnline#2]
Hey,
I am playing this on a Linux machine with Wine. Unfortunately Ctrl+Alt+Delete does not trigger the game here to load. Do you have any advice how to trigger the loading otherwise? I tried Alt+Tab, which indeed moves the focus to a different window, but it does not make the game load faster. I hope you have some deeper insight on what is happening within the game's executable and why it takes so long sometimes.
Thanks!

**Comment by Joshhhuaaa** [comment]
The goal is to get the game out of focus, so using Ctrl+Alt+Delete, Alt+Tab, or pressing the Windows key usually works on Windows. However, this method doesn’t seem to work for you on Linux for some reason. If you are somehow playing the game in a borderless window, maybe that might break this workaround since the game never loses focus.

I initially thought the problem might be related to frame rate. If your FPS is capped at 60, the game may load indefinitely or take too long to be considered playable. When you uncap your FPS, the game has about a 50/50 chance of loading instantly or within 5 seconds. If it doesn’t, you might have to wait up to 20-30 seconds. Enhanced SCDA Online uncaps the FPS during loading screens and keeps a 60 FPS lock during gameplay, which should eliminate truly "infinite" loading screens, but it may not always be instant.

I’ve noticed a pattern with the issue: if there is sound playing during the loading screen, such as lobby music when starting the game or ambient sounds from the map when loading back into the lobby, the game refuses to load until the sound stops playing. The game seems unreliable if it kills the sound during loading screens, but generally, if you hear sounds, it means you’re likely to experience a slow loading screen unless you unfocus the game.

If I were to guess, when you unfocus the game, it probably stops the audio for a split second, which might explain why this workaround works.

The console versions of the game (PS3/360) always stopped the sounds from the lobby/map during loading screens because they played a video file during those screens. This may be an oversight in the broken PC port. If someone could create a patch to kill all sound during loading screens on the PC version, it might provide consistency in loading. This is just my theory for now, it could be an entirely different issue. Either way, I wouldn’t know how to create such a patch, and the game may not have enough interest for anyone to bother.
